name: mimir
description: >
  Extremely powerful, reactive NoSQL database with
  typo-tolerant full-text search and declarative queries.
version: 0.2.1
homepage: https://github.com/GregoryConrad/mimir
repository: https://github.com/GregoryConrad/mimir
issue_tracker: https://github.com/GregoryConrad/mimir/issues
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  fixnum: ^1.1.1
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_rs: ^0.1.2+4
  protobuf: ^4.2.0 # WARN: this must match what is currently in use by protoc-gen-dart

dev_dependencies:
  ffigen: ^20.0.0
  test: ^1.22.0
