name: mimir
description: >
  Extremely powerful, reactive NoSQL database with
  typo-tolerant full-text search and declarative queries.
version: 0.1.0
homepage: https://github.com/GregoryConrad/mimir
repository: https://github.com/GregoryConrad/mimir
issue_tracker: https://github.com/GregoryConrad/mimir/issues

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  flutter_rust_bridge: 2.1.0
  freezed_annotation: ^2.2.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  ffigen: ^11.0.0
  freezed: ^2.2.1
  test: ^1.22.0
