name: example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  # These two are needed for the example; they are not required by mimir
  collection: ^1.17.0
  http: ^0.13.5
  # You can replace this with the current version of mimir
  mimir: ^0.0.0-dev.5
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
